version: "3.8"

services:
  typesense_search:
    image: typesense/typesense:29.0
    container_name: typesense
    restart: always
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    command: >
      --data-dir /data
      --api-key=uV7mQ9p4T2fA8xL1ZkC3rN6sW0bH5dE9gB4jP7qF2tM6y
      --enable-cors

volumes:
  typesense-data:
